# Cloud Build configuration for running E2E tests against deployed environments
#
# This config is used via a trigger that provides the source from GitHub.
# The trigger clones the repo, so we don't need to clone manually.
#
# Substitution variables:
#   _ENVIRONMENT: Target environment (dev, staging)
#   _COMMIT_SHA: Git commit hash of the deployed version to test
#   _ECOMMERCE_URL: URL of the ecommerce service to test against
#   _CONFIG_BUCKET: Config bucket name (e.g., breathe-staging-config)
#
# Usage (via trigger):
#   gcloud builds triggers run e2e-tests-manual \
#     --project=breathe-shared --region=europe-west2 \
#     --sha=<commit> \
#     --substitutions=_ENVIRONMENT=dev,_ECOMMERCE_URL=https://...,_CONFIG_BUCKET=breathe-dev-config

timeout: 1800s  # 30 minutes max

substitutions:
  _ENVIRONMENT: 'dev'
  _COMMIT_SHA: ''
  _ECOMMERCE_URL: ''
  _CONFIG_BUCKET: ''

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Fetch config from GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'fetch-config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching config from gs://${_CONFIG_BUCKET}/config.json"
        gsutil cp gs://${_CONFIG_BUCKET}/config.json /workspace/config.json
        echo "Config loaded successfully"

  # Step 2: Run the E2E tests
  - name: 'gradle:8.6-jdk21'
    id: 'run-tests'
    entrypoint: 'bash'
    env:
      - 'E2E_BASE_URL=${_ECOMMERCE_URL}'
      - 'GRADLE_USER_HOME=/workspace/.gradle'
    args:
      - '-c'
      - |
        set +e  # Don't exit on test failure

        echo "=============================================="
        echo "Running E2E tests against ${_ENVIRONMENT}"
        echo "Target URL: $${E2E_BASE_URL}"
        echo "Commit: ${COMMIT_SHA}"
        echo "=============================================="

        # Run tests and capture exit code
        ./gradlew :e2e-tests:test --no-daemon 2>&1 | tee /workspace/test-output.txt
        TEST_EXIT_CODE=$$?

        # Parse test results from JUnit XML reports (more reliable than console output)
        REPORT_DIR="e2e-tests/build/test-results/test"
        if [ -d "$$REPORT_DIR" ]; then
          # Count tests and failures from XML files
          TOTAL_TESTS=$$(grep -h 'tests=' $$REPORT_DIR/*.xml 2>/dev/null | grep -oP 'tests="\K\d+' | awk '{s+=$$1} END {print s}')
          TOTAL_FAILURES=$$(grep -h 'failures=' $$REPORT_DIR/*.xml 2>/dev/null | grep -oP 'failures="\K\d+' | awk '{s+=$$1} END {print s}')
          TOTAL_ERRORS=$$(grep -h 'errors=' $$REPORT_DIR/*.xml 2>/dev/null | grep -oP 'errors="\K\d+' | awk '{s+=$$1} END {print s}')

          TESTS_FAILED=$$((TOTAL_FAILURES + TOTAL_ERRORS))
          TESTS_PASSED=$$((TOTAL_TESTS - TESTS_FAILED))
        else
          # Fallback to parsing console output
          if grep -q "BUILD SUCCESSFUL" /workspace/test-output.txt; then
            TESTS_PASSED="all"
            TESTS_FAILED="0"
          else
            TESTS_PASSED=$$(grep -oP '\d+(?= tests completed)' /workspace/test-output.txt | tail -1 || echo "?")
            TESTS_FAILED=$$(grep -oP '\d+(?= failed)' /workspace/test-output.txt | tail -1 || echo "?")
          fi
        fi

        # Write results for notification step
        echo "$${TEST_EXIT_CODE}" > /workspace/test-exit-code.txt
        echo "$${TESTS_PASSED}" > /workspace/tests-passed.txt
        echo "$${TESTS_FAILED}" > /workspace/tests-failed.txt

        echo ""
        echo "Test results: $${TESTS_PASSED} passed, $${TESTS_FAILED} failed"

        exit 0  # Always succeed so we can send notification

  # Step 3: Send Slack notification using config from GCS
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify-slack'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Extract Slack config from config.json
        SLACK_BOT_TOKEN=$$(cat /workspace/config.json | grep -oP '"botToken"\s*:\s*"\K[^"]+')
        SLACK_CHANNEL=$$(cat /workspace/config.json | grep -oP '"notificationChannelId"\s*:\s*"\K[^"]+')

        if [ -z "$$SLACK_BOT_TOKEN" ] || [ -z "$$SLACK_CHANNEL" ]; then
          echo "Warning: Could not extract Slack config from config.json"
          echo "Skipping Slack notification"
          exit 0
        fi

        TEST_EXIT_CODE=$$(cat /workspace/test-exit-code.txt)
        TESTS_PASSED=$$(cat /workspace/tests-passed.txt 2>/dev/null || echo "?")
        TESTS_FAILED=$$(cat /workspace/tests-failed.txt 2>/dev/null || echo "?")

        # Determine status
        if [ "$${TEST_EXIT_CODE}" = "0" ]; then
          STATUS_EMOJI=":white_check_mark:"
          STATUS_TEXT="Passed"
          COLOR="#36a64f"
        else
          STATUS_EMOJI=":x:"
          STATUS_TEXT="Failed"
          COLOR="#dc3545"
        fi

        # Build Slack message
        COMMIT_SHORT=$$(echo "${COMMIT_SHA}" | cut -c1-8)
        BUILD_URL="https://console.cloud.google.com/cloud-build/builds;region=europe-west2/$${BUILD_ID}?project=breathe-shared"

        cat > /workspace/slack-payload.json << SLACK_EOF
        {
          "channel": "$${SLACK_CHANNEL}",
          "attachments": [
            {
              "color": "$${COLOR}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "$${STATUS_EMOJI} E2E Tests $${STATUS_TEXT} - ${_ENVIRONMENT}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Environment:*\n${_ENVIRONMENT}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<https://github.com/jpartner/breathe-java/commit/${COMMIT_SHA}|$${COMMIT_SHORT}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Tests Passed:*\n$${TESTS_PASSED}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Tests Failed:*\n$${TESTS_FAILED}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "<${_ECOMMERCE_URL}|Service URL> | <$${BUILD_URL}|Build Logs>"
                    }
                  ]
                }
              ]
            }
          ]
        }
        SLACK_EOF

        # Send to Slack using chat.postMessage API
        RESPONSE=$$(curl -s -X POST https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer $${SLACK_BOT_TOKEN}" \
          -H "Content-type: application/json" \
          --data @/workspace/slack-payload.json)

        # Check response
        if echo "$$RESPONSE" | grep -q '"ok":true'; then
          echo "Slack notification sent successfully to channel $${SLACK_CHANNEL}"
        else
          echo "Warning: Slack notification may have failed"
          echo "Response: $$RESPONSE"
        fi

  # Step 4: Fail the build if tests failed (after notification)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'check-results'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TEST_EXIT_CODE=$$(cat /workspace/test-exit-code.txt)
        if [ "$${TEST_EXIT_CODE}" != "0" ]; then
          echo "E2E tests failed with exit code $${TEST_EXIT_CODE}"
          exit 1
        fi
        echo "E2E tests passed!"
